v0.1.1 make real script

diff --git a/genisys-bootstrap-customer b/genisys-bootstrap-customer
--- a/genisys-bootstrap-customer
+++ b/genisys-bootstrap-customer
@@ -1,3 +1,155 @@
-#!/bin/sh
+#!/bin/bash
 
-curl -v -H 'Content-Type: application/json' -X PATCH https://$(jq -r '.uuid' ./super-user/meshblu.json):$(jq -r '.token' ./super-user/meshblu.json)@factory-service.dev.octo.space/v2/customers/$(jq -r '.uuid' ./customer/meshblu.json) -d '{"configurationUrl": "https://raw.githubusercontent.com/octoblu/smartspaces-bootstrap-configuration/master/development.json"}'
+SCRIPT_NAME='genisys-bootstrap-customer'
+
+matches_debug() {
+  if [ -z "$DEBUG" ]; then
+    return 1
+  fi
+  if [[ $SCRIPT_NAME == $DEBUG ]]; then
+    return 0
+  fi
+  return 1
+}
+
+debug() {
+  local cyan='\033[0;36m'
+  local no_color='\033[0;0m'
+  local message="$@"
+  matches_debug || return 0
+  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
+}
+
+script_directory(){
+  local source="${BASH_SOURCE[0]}"
+  local dir=""
+
+  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
+    dir="$( cd -P "$( dirname "$source" )" && pwd )"
+    source="$(readlink "$source")"
+    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+  done
+
+  dir="$( cd -P "$( dirname "$source" )" && pwd )"
+
+  echo "$dir"
+}
+
+assert_required_params() {
+  local subdomain="$1"
+
+  if [ -n "$subdomain" ]; then
+    return 0
+  fi
+
+  usage
+
+  if [ -z "$subdomain" ]; then
+    echo "Missing subdomain argument"
+  fi
+
+  exit 1
+}
+
+usage(){
+  echo "USAGE: ${SCRIPT_NAME}"
+  echo ''
+  echo 'Description: ...'
+  echo ''
+  echo 'Arguments:'
+  echo '  -h, --help       print this help text'
+  echo '  -v, --version    print the version'
+  echo ''
+  echo 'Environment:'
+  echo '  DEBUG            print debug output'
+  echo ''
+}
+
+version(){
+  local directory="$(script_directory)"
+
+  if [ -f "$directory/VERSION" ]; then
+    cat "$directory/VERSION"
+  else
+    echo "unknown-version"
+  fi
+}
+
+panic(){
+  local message="$1"
+  echo "$message"
+  exit 1
+}
+
+main() {
+  local subdomain
+  # Define args up here
+  while [ "$1" != "" ]; do
+    local param="$1"
+    local value="$2"
+    case "$param" in
+      -h | --help)
+        usage
+        exit 0
+        ;;
+      -v | --version)
+        version
+        exit 0
+        ;;
+      -s | --subdomain)
+        subdomain="$value"
+        shift
+        ;;
+      *)
+        if [ "${param::1}" == '-' ]; then
+          echo "ERROR: unknown parameter \"$param\""
+          usage
+          exit 1
+        fi
+        ;;
+    esac
+    shift
+  done
+
+  assert_required_params "$subdomain"
+
+  if [ "$subdomain" == "dev" ]; then
+    configurationUrl="https://raw.githubusercontent.com/octoblu/smartspaces-bootstrap-configuration/master/development.json"
+  else
+    configurationUrl="https://raw.githubusercontent.com/octoblu/smartspaces-bootstrap-configuration/master/semi-stable.json"
+  fi
+
+  if [ ! -f "./super-user/meshblu.json" ]; then
+    panic "Error: ./super-user/meshblu.json not found"
+  fi
+
+  if [ ! -f "./customer/meshblu.json" ]; then
+    panic "Error: ./customer/meshblu.json not found"
+  fi
+
+  local superUserUuid="$(jq -r '.uuid' ./super-user/meshblu.json)"
+  local superUserToken="$(jq -r '.token' ./super-user/meshblu.json)"
+  local customerUuid="$(jq -r '.uuid' ./customer/meshblu.json)"
+
+  if [ "$superUserUuid" == "" ]; then
+    panic "Error: super-user uuid not found"
+  fi
+
+  if [ "$superUserToken" == "" ]; then
+    panic "Error: super-user token not found"
+  fi
+
+  if [ "$customerUuid" == "" ]; then
+    panic "Error: customer uuid not found"
+  fi
+
+  curl --fail \
+    -H 'Content-Type: application/json' \
+    -X PATCH "https://$superUserUuid:$superUserToken@factory-service.$subdomain.octo.space/v2/customers/$customerUuid" \
+    -d "{\"configurationUrl\": \"$configurationUrl\"}" \
+  || panic "Error: Update failed" \
+  && echo "OK"
+
+}
+
+main "$@"
