v4.3.0 Add --domain override to genisys-create-admin

diff --git a/genisys-create-admin b/genisys-create-admin
--- a/genisys-create-admin
+++ b/genisys-create-admin
@@ -91,6 +91,7 @@ usage(){
   echo '             device.'
   echo ''
   echo 'Arguments:'
+  echo '  -d, --domain     overrides the domain from the customer device'
   echo '  -e, --email      the desired email address for the new admin account'
   echo '  -h, --help       print this help text'
   echo '  -p, --password   the desired login password for the new admin account'
@@ -117,10 +118,14 @@ create_admin_account() {
   email="$1"
   password="$2"
   meshblu_json_path="$3"
+  domain="$4"
 
   customer_uuid="$(jq --raw-output '.uuid' "$meshblu_json_path")" || fatal "could not get uuid for customer"
   customer_token="$(jq --raw-output '.token' "$meshblu_json_path")" || fatal "could not get token for customer"
-  domain="$(get_domain "$meshblu_json_path")" || fatal "could not retrieve domain"
+
+  if [ -z "$domain" ]; then
+    domain="$(get_domain "$meshblu_json_path")" || fatal "could not retrieve domain"
+  fi
 
   post_new_admin "$customer_uuid" "$customer_token" "$domain" "$email" "$password" \
   && echo "" \
@@ -155,13 +160,17 @@ post_new_admin(){
 }
 
 main() {
-  local email meshblu_json_path password
+  local domain email meshblu_json_path password
 
   # Define args up here
   while [ "$1" != "" ]; do
     local param="$1"
     local value="$2"
     case "$param" in
+      -d | --domain)
+        domain="$value"
+        shift
+        ;;
       -e | --email)
         email="$value"
         shift
@@ -207,7 +216,7 @@ main() {
   assert_required_params "$email" "$password" "$meshblu_json_path"
   assert_is_customer "$meshblu_json_path"
 
-  create_admin_account "$email" "$password" "$meshblu_json_path"
+  create_admin_account "$email" "$password" "$meshblu_json_path" "$domain"
 }
 
 main "$@"
